language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

branches:
    only:
      - staging

env: DJANGO_SETTINGS_MODULE="bp_project.settings"

services:
  - postgresql

script:
  - ./manage.py test