language: python3
python:
  - '3.7'

# safelist
branches:
  only:
    - staging

before_script:
  - pip3 install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="bp_project.settings.travis"

script:
  - python3 manage.py test
